poetrynet/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

from dajaxice.core import dajaxice_autodiscover
dajaxice_autodiscover()

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'poetrynet.views.home', name='home'),
    # url(r'^poetrynet/', include('poetrynet.foo.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/$', settings.MEDIA_ROOT),
    url(r'^accounts/', include('userena.urls')),
    url(r'^$', 'poetrynet.frontpage.views.home', name='home'),
    url(r'^contact/$', 'poetrynet.frontpage.views.contact', name='contact'),
    url(r'^instructions/$', 'poetrynet.frontpage.views.instructions', name='instructions'),
    url(r'^allpoems/$', 'poetrynet.frontpage.views.allpoems', name='allpoems'),
    url(r'^poems/', include('poetrynet.poems.urls')),
    #Dajax URLS
    url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),
)

poetrynet/poems/models.py
from django.db import models
from django.contrib.auth.models import User

from django.shortcuts import get_object_or_404
import random

#import pickle_fields, pickle_tests
from picklefield.fields import PickledObjectField

#FLOODING_TOLERANCE_CHOICES = (
#    (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'),
#)

#PUNCTUATION_WEIGHT_CHOICES = (
#    (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'),
#)


class PoemOptions(models.Model):
    """
    The custom options of a poem, decoupled from the poem itself because all of that data isn't needed at every step.
    Also, the default optionset is id=1.
    """

    ####COMMON OPTIONS (SOCIAL OPTIONS)####
    max_simultaneous_authors = models.IntegerField("Max simultaneous authors",help_text="Maximum users that can participate in the creation of this poem at once. 0 means no limit!", default=0)
    no_user_list = models.BooleanField(help_text="Hide the list of authors until the poem is published for the first time.", default=False)
    #no_chatting = models.BooleanField(help_text="Disallow private messaging in this poem-session.", default=False)
    #not an option now but a possibile one -- switch for whether Client display shows "how many words till next crush" or somn.
    
    ####LESS COMMON OPTIONS (PARAMETERS)####
    #invite_only = models.BooleanField(help_text="Do users need to be invited to this poem?", default=False)
    #max_total_authors = models.IntegerField(help_text="Maximum users that can participate in the creation of this poem overall. 0 means no limit", default=0)
    #authorship_public = models.BooleanField("Author visibility", help_text="Display authorship to public?", default=True)
    max_length = models.IntegerField("Maximum length", help_text="Optional maximum length of poem/session (in outputs/rounds). 0 means no limit!", default=0)
    
    ####ADVANCED OPTIONS (MECHANICS)####
    #flooding_tolerance = models.IntegerField(help_text="Tolerance for input-floods from a given user. 0 is no tolerance, 9 is unpatrolled", choices=FLOODING_TOLERANCE_CHOICES, default=5)
    #logopoeia_weight = models.IntegerField(help_text="Logopoeia % chance.", default="34")
    #phanopoeia_weight = models.IntegerField(help_text="Phanopoeia % chance.", default="33")
    #melopoeia_weight = models.IntegerField(help_text="Melopoeia % chance.", default="33")
    #punctuation_weight = models.IntegerField(help_text="How much of the inputted punctuation to preserve? 0 is none, 9 is as much as possible", choices=PUNCTUATION_WEIGHT_CHOICES, default=5)
    #related_poem = models.CharField("Related poem", help_text="Refer the algorithm back to another poem on this website? To utilize this option, type the title of that poem verbatim.", max_length=255, blank=True, null=True, default=" ")
    #no_meta = models.BooleanField("No meta characters", help_text="Disallow metacharacters like <w>, <italics>, etc.", default=False)
    #no_proper_nouns = models.BooleanField(help_text="Disallow proper nouns", default=False)
    #no_gibberish = models.BooleanField(help_text="Disallow gibberish", default=False)
    #freeze = models.BooleanField(help_text="Freeze poem after publishing?", default=False)
    #absorb_chatting = models.BooleanField(help_text="Experimental option -- whether to absorb private messages uttered in this room into the poem's corpus.", default=False)

class PoemStats(models.Model):
    
    ####ROBO-MANAGED FIELDS & VARIABLES####
    #max_utterances = models.IntegerField(help_text="Number of utterances in each cluster; this should get updated each time a user joins/leaves", default=2)
    utterances = models.IntegerField(help_text="...", default=0)
    
    views = models.IntegerField("Views", help_text="Views since first publishing.", default=0)
 
    active_authors = models.ManyToManyField(User, through='Ping', related_name="AC")
    loading = models.IntegerField("Metertag - Loading?", help_text="Yes/no", default=0)
    serving = models.BooleanField("Spinner-Cursor Boolean", help_text="While a cluster is being postprocessed a spinner is displayed, this is the flag for whether it is or not.", default=False)
    last_sentence = models.CharField(help_text="Stuff since last 'end of sentence marker', i.e. newline, period, caps, etc.", blank=True, null=True, default="~", max_length=256)
    last_benchmark = models.TextField(help_text="Can be: [.;%] meaning EOS; C (or J) meaning centreme (or adj/adv cent); or X|word for non-centreme words", default=".")
    clusters_computed = models.IntegerField(help_text="i.e. what round is this.", default=0)
    
    ####CODES & INTERNAL WORKINGS####
    code = models.CharField(help_text="A seed-code used throughout the algorithms. Must be 10 digits long.", max_length=10, default="0123456789")
    step = models.IntegerField(help_text="Step 0-9 in the code.", max_length=1, default=0)
    walking_forward = models.BooleanField(help_text="Are we moving right (True) or left (False) through the code?", default=True)
    mode_key = models.CharField(help_text="A 10-digit reference for WHAT MODE to use.", max_length=10, default="1122331233")
    #cleanup_flag = models.IntegerField(help_text="Incremented each time a cluster is cooked, so that certain things can be done every N cluster-cookings", default=0)

class Poem(models.Model):
    created_date = models.DateTimeField(help_text="When first created", auto_now_add=True)
    pub_date = models.DateTimeField("Date published", help_text="When first published", blank=True, null=True) #poems should not be listed in listings-for-reading until published.
    authors = models.ManyToManyField(User, related_name="AU")
    stats = models.ForeignKey(PoemStats)
    creator = models.ForeignKey(User, related_name="CR")
    
    ####ESSENTIAL OPTIONS####
    title = models.CharField(max_length=255, unique=True)
    welcome_message = models.TextField("Welcome message",
                                        default="Welcome.",
                                        help_text="Displayed to each user upon joining the poem-session. Not displayed with the published poem.")
    
    ####EXTRA OPTIONS####
    customized = models.BooleanField("Customization", help_text="Fine-tune the options of this poem-session?", default=False)
    options = models.ForeignKey(PoemOptions)
        
    #facade: textual representation of this poem. this is the last way this poem looked
    #when it was saved last (usually that means: the final or last appearance of the poem
    #from the performance that generated it). when a poem is shuffled again, that creates
    #an appearance for the client who has shuffled it; but they'd need to save a new Poem
    #from that, if they wanted to preserve that appearance (and that Poem object's 'facade'
    #would be, indeed, the textual representation at the time of their save.
    facade = models.TextField(help_text="Last textual representation of this poem -- (cheaply) HTML formatted, _NOT_ plaintext!!")
    html = models.TextField(help_text="HTML-ified-version")
    basepickle = PickledObjectField(help_text="Pickled data representing the poem's content-words (plus other important words) in order of appearance.")
    phanopickle = PickledObjectField(help_text="Pickled data representing the poem's chains made by lettristic functions.")
    melopickle = PickledObjectField(help_text="Pickled data representing the poem's chains made by melopoeiac functions.")
    
    def newCluster(self):
        """makes the first cluster for this poem."""
        try:
            c = Cluster(poem=self)
            c.save()
            return c
        except:
            try:
                c = Cluster(poem=self)
                c.save()
                return c
            except:
                return None
    
    def shuffle(self):
        clusters = Cluster.objects.filter(poem=self.pk)
        #not completed. this should be the "reshuffle" ability. reshuffles EVERYTHING. not relevant yet ..
        pass 
    
    def save(self, *args, **kwargs):
        #pre-super:
        firsttime=False
        if self.id is None:
            firsttime=True
        super(Poem, self).save(*args, **kwargs) #Call the "real" save() method ...
        if firsttime:
            self.newCluster()
        #post-super:
    
    def __unicode__(self):
        return unicode(self.title)

class Ping(models.Model):
    """Logs (and cleans up) records of who is pinging what poems..."""
    poemstats = models.ForeignKey(PoemStats)
    user = models.ForeignKey(User)
    date = models.DateTimeField("Date created.", auto_now_add=True) 
    
class Cluster(models.Model):
    """A collection of user inputs sent to the same poem at the same step of writing it."""
#    utterances = models.ManyToManyField(Usaving a tterance, through='UtteranceMembership')
    poem  = models.ForeignKey(Poem)
    #The field below, max_utterances, seems like it may in fact be deprecated.
    #max_utterances = models.IntegerField("Number of utterances-per-cluster at the time this cluster was CRUSHED. (For reference in later shuffles.)", default=7)
    facade = models.CharField("Last textual representation of this cluster", max_length=160, blank=True, null=True, default="")
    html = models.CharField("HTML version of facade", max_length=255, blank=True, null=True, default="")
    date = models.DateTimeField("Date created.", help_text="When cluster was born.", auto_now_add=True)
    crushstate = models.IntegerField( default=0)
    lock_date = models.DateTimeField("For locking.", help_text="When this cluster was locked.", null=True, blank=True, default=None)
    pickle = PickledObjectField(help_text="This is the pickled cluster, saved here when cookCluster has cooked it. pickle[0]=(anteme,centreme,posteme); pickle[1]={Cooked-but-not-served results string}",  null=True, blank=True, default=None)

templates/by.html
{% extends "site_base.html" %}
{% load i18n %}

{% block title %}Poems by {{ user }}{% endblock %}
	

{% block content_header %}
	Poems <a href="/accounts/{{user}}/">{{ user }}</a> has participated in
{% endblock %}

{% block content %}
		<p>
			<ul class="arrows">
				{% for poem in poems %}
					<li><a href="/poems/view/{{poem.id}}">{{poem.title}}</a></li>
				{% endfor %}
			</ul>
		</p>
{% endblock %}

templates/create_poem.html
{% extends "site_base.html" %}
{% block title %} New Poem {% endblock %}

{% block dj_head %}
	{% include "dj_head_jquery.html" %}
{% endblock %}


{% block left_bar %}
	<div id="left">
		<h1>Your Poems</h1>
		<div id="yourpoems">{% autoescape off %}{{ yourpoems }}{% endautoescape %}</div>
	</div>
{% endblock %}

{% block content_header %} New Poem-Session{% endblock %}

{% block content %}
	<!--[if IE]><p style="color:#FF0000">It appears that you are using Internet Explorer.
	There is a known bug where this form <b>does not work</b> on any version of Internet Explorer
	(however, the rest of the site should work fine; you can join other poems and participate that way).
	We would recommend using another browser like <a href="http://www.mozilla.org/en-US/firefox/" target="_blank">Firefox</a> anyways!
	</p><![endif]-->
	<p><blockquote>&laquo; <a href="/">Home</a> | <a href="/instructions/">Instructions</a> &raquo;</blockquote></p>
	{% if user.is_authenticated %}
		<form action="" method="post" accept-charset="utf-8">
			
				{% csrf_token %}
			    {{ main_form.non_field_errors }}
			    <table border='0'>
				    {% for field in main_form %}
				    	<tr>
						    <td>
							    <b>{{ field.label_tag }}</b><br/>
							    <p class="smaller">{{ field.help_text }}</p>
							</td>
							<td>
							    {{ field }}
							    {% if field.errors %}
							    	<p class="smaller">{{ field.errors }}</a>
							    {% endif %}
						    </td>
					    </tr>
				    {% endfor %}
				</table>
			
			
			<div class="hiddenextra" id="poem_options_form">
				<form action="" method="post">
					{% csrf_token %}
				    {{ options_form.non_field_errors }}
				    <table border='0'>
					    {% for field in options_form %}
					    	<tr>
					    		{% if field.name == "related_poem" %}
								    <td colspan="2">
									    <span>
									    	<b>{{ field.label_tag }}</b>
									    </span>
									    <span class="smaller">
										    {{ field }}
										    {% if field.errors %}
										    	{{ field.errors }}
										    {% endif %}
										</span>
										<p class="smaller">{{ field.help_text }}</p>
								    </td>
								{% else %}
									<td class="weirdformat">
									    {{ field }}
		
								    </td>
								    <td>
									    <b>{{ field.label_tag }}</b><br/>
									    <p class="smaller">{{ field.help_text }}</p>
									    {% if field.errors %}
									    	<p class="smaller">{{ field.errors }}</p>
									    {% endif %}
									</td>
								{% endif %}
						    </tr>
					    {% endfor %}
					</table>				

			</div>
			
			<table><tr><td><span><button type="submit" />Create Poem & Start Writing</button></span></td></tr></table>
			
		</form>
		
		
		{% if not options_form_errors %}
			<script>$("#poem_options_form").css("display","none");</script>
		{% else %}
			<script>$("#poem_options_form").show("fast");</script>
		{% endif %}
		<script>
		    $("#id_customized").click(function () {
		    	// If checked
				if ($("#id_customized").is(":checked"))
				{
					//show the hidden div
					$("#poem_options_form").show("fast");
				}
				else
				{
					//otherwise, hide it
					$("#poem_options_form").hide("fast");
				}
		    });
		</script>

	{% else %}
		<p>Only registered users can create a new poem. It only takes a second -- <a href="/accounts/signup/">register here</a>.</p>
		<p class="smaller">Or perhaps you just want to go <a href="/">home</a>?</p>
	{% endif %}
{% endblock %}

templates/dajax_client.html
{% extends "site_base.html" %}

{% block title %}Writing {{poem.title}} | poetry.party{% endblock %}
{% block extrahead %}
	<script>
		var images = ["/static/img/meter/0.gif",
		"/static/img/meter/1.gif",
		"/static/img/meter/2.gif",
		"/static/img/meter/99.gif",
		"/static/img/meter/777.gif",];
		for (i = 0; i < preload.length; i++) {
		    images[i] = new Image();
		    images[i].src = preload[i];
		}
 
	</script>

{% endblock %}


{% block left_bar %}{% endblock %}

{% block content_header %}{{poem.title}}{% endblock %}
{% block print %}<div id="printcontainer"> <a href="/poems/print/{{poem.id}}/" target="_blank"><img id="print" src="/static/img/print.png" alt="Print-friendly (and copy-&-paste friendly) view of this poem." /></a> </div> {% endblock %}
{% block content %}
	<div class="wrappa">
		<div id="windeyelid">
			<div class="plike" id="windeye">
				<div id="windeyetext">
					{% autoescape off %}
						
					{% endautoescape %}
					<img id="meterimg" src="/static/img/arrows.gif" alt="Retrieving poem ..." />
				</div>
			</div>
			<div id="metercontainer">
				<div id="meter"><img id="meterimg" src="/static/img/meter/99.gif" alt="Loading..." /></div>
			</div>
		</div>
	</div>
	<div class="wrappa">
		<div class="plike">
			{% if not full_house %}
				<form id="inform" onsubmit="Dajaxice.poetrynet.poems.senditin(Dajax.process,{'input':$('talkbox').value, 'poem_id':{{poem.id}} }, {'error_callback': custom_error}); return false;">
					<div><span id="lastwords" class="notification">Type words & punctuation in the box below.</span><br/></div>
					<div>
						<input type="text" name="talkbox" id="talkbox" class="input" size="46" value="" autocomplete="off" maxlength="1000" />
						<button type="submit" name="submit" id="submit" class="button">Submit</button>
					</div>
				</form>
			{% else %}
			<h2><a class="tooltip" href="#">Poem is still writable, but full.
			<span class="classic">The poem's limit on simultaneous authors has been reached. If you think a user has left the poem, you must <b>refresh the page</b> in order to join.</span></a></h2>
			{% endif %}
		</div>
	</div>
{% endblock %}
{% block right_bar %}
	<div id="right">
		{% include 'right_client.html' %}
	</div>
{% endblock %}

{% block extraright_bar %}
	<div id="extraright">
		{% include 'extraright_client.html' %}
	</div>
{% endblock %}


{% block extrafoot %}

	<script>
	   new Ajax.PeriodicalUpdater('windeyelid', "{% url poems.views.poll id=poem.id %}", {
	     method: 'get', frequency: 1 {% comment %}, decay: 1.1 <-- if we start getting too slow.{% endcomment %}
	   });

	</script>

{% endblock %}

templates/dj_head_jquery.html
<script src="http://www.google.com/jsapi"></script>
<script>

    //google.load("prototype", "1.6.0.3");
    google.load("jquery", "1.3.2");
    //google.load("mootools", "1.2.1");
    //google.load("dojo", "1.3.1");
    
    /**
    Callback test
    **/
    
    function my_callback(data){
        alert(data+' received from server');
    }
</script>


{% include "djfix.html" %}


<script type="text/javascript" charset="utf-8">
	/* Copyright (c) 2009-2010, Benito Jorge Bastida :: For further information check COPYING */
	var Dajax = Class.create();
	Dajax.prototype = {
	    initialize: function(){},
	    process: function(data)
	    {
	        if(data==Dajaxice.EXCEPTION){
	            alert('Something went wrong, please reload the page.');
	        }
	        else{
	            data.each(function(elem){
	            switch(elem.cmd)
	            {
	                case 'alert':
	                    alert(elem.val)
	                break;
	        
	                case 'data':
	                    eval( elem.fun+"(elem.val);" );
	                break;
	        
	                case 'as':
	                    $$(elem.id).each(function(e){e[elem.prop] = elem.val;});
	                break;
	        
	                case 'addcc':
	                    elem.val.each(function(cssclass){
	                        $$(elem.id).each(function(e){ e.addClassName(cssclass);});
	                    });
	                break;
	        
	                case 'remcc':
	                    elem.val.each(function(cssclass){
	                        $$(elem.id).each(function(e){ e.removeClassName(cssclass);});
	                    });
	                break;
	        
	                case 'ap':
	                    $$(elem.id).each(function(e){ e[elem.prop] += elem.val;});
	                break;
	        
	                case 'pp':
	                    $$(elem.id).each(function(e){ e[elem.prop] = elem.val + e[elem.prop];});
	                break;
	        
	                case 'clr':
	                    $$(elem.id).each(function(e){e[elem.prop] = "";});
	                break;
	        
	                case 'red':
	                    window.setTimeout('window.location="'+elem.url+'";',elem.delay);
	                break;
	        
	                case 'js':
	                    eval(elem.val);
	                break;
	        
	                case 'rm':
	                    $$(elem.id).each(function(e){e.remove();});
	                break;
	        
	                default:
	                    alert('Unknown action!');
	                }
	            });
	        }
	    }
	};
	
	Dajax = new Dajax();
	
	function custom_error(){
		alert('Error with text input somewhere ...');
	}
	
</script>

templates/dj_head_prototype.html
<script src="http://www.google.com/jsapi"></script>
<script>
    // Load Prototype
    google.load("prototype", "1.6.0.3");
    //google.load("jquery", "1.3.2");
    //google.load("mootools", "1.2.1");
    //google.load("dojo", "1.3.1");
    
    /**
    Callback test
    **/
    
    function my_callback(data){
        alert(data+' received from server');
    }
</script>

{% include "djfix.html" %}

<script type="text/javascript" charset="utf-8">
	/* Copyright (c) 2009-2010, Benito Jorge Bastida :: For further information check COPYING */
	var Dajax = Class.create();
	Dajax.prototype = {
	    initialize: function(){},
	    process: function(data)
	    {
	        if(data==Dajaxice.EXCEPTION){
	            alert('Something went wrong, please reload the page.');
	        }
	        else{
	            data.each(function(elem){
	            switch(elem.cmd)
	            {
	                case 'alert':
	                    alert(elem.val)
	                break;
	        
	                case 'data':
	                    eval( elem.fun+"(elem.val);" );
	                break;
	        
	                case 'as':
	                    $$(elem.id).each(function(e){e[elem.prop] = elem.val;});
	                break;
	        
	                case 'addcc':
	                    elem.val.each(function(cssclass){
	                        $$(elem.id).each(function(e){ e.addClassName(cssclass);});
	                    });
	                break;
	        
	                case 'remcc':
	                    elem.val.each(function(cssclass){
	                        $$(elem.id).each(function(e){ e.removeClassName(cssclass);});
	                    });
	                break;
	        
	                case 'ap':
	                    $$(elem.id).each(function(e){ e[elem.prop] += elem.val;});
	                break;
	        
	                case 'pp':
	                    $$(elem.id).each(function(e){ e[elem.prop] = elem.val + e[elem.prop];});
	                break;
	        
	                case 'clr':
	                    $$(elem.id).each(function(e){e[elem.prop] = "";});
	                break;
	        
	                case 'red':
	                    window.setTimeout('window.location="'+elem.url+'";',elem.delay);
	                break;
	        
	                case 'js':
	                    eval(elem.val);
	                break;
	        
	                case 'rm':
	                    $$(elem.id).each(function(e){e.remove();});
	                break;
	        
	                default:
	                    alert('Unknown action!');
	                }
	            });
	        }
	    }
	};
	
	Dajax = new Dajax();
	
	function custom_error(){
		alert('A strange error has occurred. Please refresh the page. If this error persists, please try a different browser or computer; unfortunately, the cause of this bug is yet unknown.  Please contact the webmaster!');
	}
	
</script>

templates/djfix.html
{% comment %}
	{% load dajaxice_templatetags %}
	{% dajaxice_js_import "/static/js/dajaxice.core.js" %}
{% endcomment %}
<script src="/static/js/dajaxice.core.js" type="text/javascript" charset="utf-8"></script>

templates/extraright_client.html
{% if poem.pub_date %}
	<h1><a class="tooltip" href="#">Authors<span class="classic">All users who interacted with this poem during its writing.</span></a></h1>
	<ul>
		{% for x in poem.authors.all %}
			<li><a href="/poems/by/{{x}}">{{x}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<h1><a class="tooltip" href="#">Active Authors<span class="classic">All users who have interacted with this poem within the last thirty seconds.</span></a></h1>
	{% if not poem.options.no_user_list %}
		<ul id="ac">
				{% for x in poem.stats.active_authors.all %}
					<li><a href="/poems/by/{{x}}">{{x}}</a></li>
				{% endfor %}
	
		</ul>
	{% else %}
		<p>The Active Authors list was disabled for this poem.</p>
	{% endif %}

	<script>
	   new Ajax.PeriodicalUpdater('ac', "{% url poems.views.userlist id=poem.id %}", {
	     method: 'get', frequency: 4
	   });

	</script>
{% endif %}

templates/kiosk.html
{% extends "site_base.html" %}
{% load dajaxice_templatetags %}

{% block title %}{{poem.title}} | poetry.party{% endblock %}
{% block dj_head %}
	{% include "dj_head_prototype.html" %}
{% endblock %}



{% block left_bar %}{% endblock %}

{% block content_header %}{{poem.title}}{% endblock %}
{% block print %}<div id="printcontainer"> <a href="/poems/print/{{poem.id}}/"><img id="print" src="/static/img/print.png" alt="Print-friendly (and copy-&-paste friendly) view of this poem." /></a> </div> {% endblock %}

{% block content %}
	<div class="wrappa">
		<div id="windeyelid">
			<div class="plike" id="windeye">
				<div id="windeyetext">
					{% autoescape off %}
						Retrieving poem ...
					{% endautoescape %}
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block right_bar %}
	<div id="right">
		{% include 'right_client.html' %}
	</div>
{% endblock %}

{% block extraright_bar %}
	<div id="extraright">
		{% include 'extraright_client.html' %}
	</div>
{% endblock %}


{% block extrafoot %}

	<script>
	   new Ajax.PeriodicalUpdater('windeyelid', "{% url poems.views.getpoem id=poem.id %}", {
	     method: 'get', frequency: 1
	   });

	</script>

{% endblock %}

templates/left.html
{% if user.is_authenticated %}
	<h1>Your poems</h1>
	<div id="yourpoems"></div>
	<script>
	   new Ajax.Updater('yourpoems', "{% url poems.views.yours %}", {
	     method: 'get'
	   });
	</script>
{% else %}
	<h1>Get started</h1>
	<p>Start by <a href="/instructions/">reading the instructions</a>, <a href="/poems/guest/">signing in as a guest</a>, or <a href="/accounts/signup/">registering</a> your username.</p>
{% endif %}

templates/logo.html
<div id="logo">

<a href="/">
  poetry.party | dadaconf 0
</a>
</div>

templates/plain.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title>[Printable] {{poem.title}} | poetry.party</title>
	
</head>

<body>
<pre><b>Printable view of <a href="/poems/view/{{poem.id}}">{{poem.title}}</a>  | <a href="/">poetry.party</a></b></pre>
<blockquote>
	<pre><i>by</i> {% for x in poem.authors.all %}{{x}}{% if not forloop.last %},{% endif %} {% endfor %}</pre>
	<blockquote>
		{% if poem.pub_date %}
		<pre><i>Published</i> {{ poem.pub_date }}</pre>
		{% else %}
		<pre><i>Unpublished.</i> Accessed at {{ accessed }}. </pre>
		{% endif %}
	</blockquote>


	<br/>

	<pre><b>{{poem.title}}</b></pre>
	<pre>{% autoescape off %}{{formatted_facade}}{% endautoescape %}</pre>
	</pre>
</blockquote>
</body>

templates/right_client.html
<h1>About&nbsp;&nbsp;</h1>
{% if poem.pub_date %}
{% else %}
	{% if poem.welcome_message != 'Welcome.' %}
	<p class="smaller">{{poem.welcome_message}}</p>
	<h2>More about this poem</h2>
	{% endif %}
{% endif %}

<ul class="arrows">

	{% if poem.options.max_simultaneous_authors %}
		<li>Max active authors: {{poem.options.max_simultaneous_authors}}</li>
	{% endif %}
	

	
	<li>
		{% if poem.pub_date %}
			Published: {{poem.pub_date}}
		{% else %}
			Created: {{poem.created_date}}
		{% endif %}
	</li>
	
	<li>Views: {{poem.stats.views}}</li>

</ul>
	{% if not poem.pub_date and poem.creator.id == user.id %}
		<p style="text-align:center;"><b><a href="/poems/publish/{{poem.id}}/" >Publish &raquo;</a></b></p>
	{% endif %}